[tool.pylint.messages_control]

disable = [
    "missing-function-docstring",
    "missing-final-newline",
    "missing-class-docstring",
    "missing-module-docstring",
    "invalid-name",
    "too-few-public-methods"
]

[tool.black]
line-length = 88
target-version = ['py39']
skip-string-normalization = false

[tool.isort]
multi_line_output = 3
length_sort = true

[tool.coverage.run]
branch = false
omit = ["no_funciona.py", "*__init__.py", "lambda_function.py"]
