# version: "3.8"
services:
  backend:
    image: ${LOCAL_IMAGE_NAME}
    ports:
      - "8080:8080"
    network_mode: bridge
    environment:
      - PREDICTIONS_STREAM_NAME=${PREDICTIONS_STREAM_NAME}
      - RUN_ID=123
      - AWS_DEFAULT_REGION=us-east-1
      - MODEL_BUCKET=nrf-mlflow
      - EXPERIMENT_ID=1
      - MODEL_LOCATION=/app/model
      - KINESIS_ENDPOINT_URL=http://localstack:4566/
    volumes:
      - "./model:/app/model"
    depends_on:
      localstack:
        condition: service_started
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - SERVICES=kinesis
      - DEFAULT_REGION=us-east-1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_EXECUTOR=docker-reuse
      - LAMBDA_REMOVE_CONTAINERS=true
      - LAMBDA_REMOTE_DOCKER=false
